repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.12.0
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts
          - --output-file=README.md
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      - id: ruff
        args: [--config, ruff.toml, --fix]
      - id: ruff-format
        args: [--config, ruff.toml]
